### ISSUE TITLE
YOLOv3-SPP Pruned-Quantized downloading a different model?

### ISSUE THREAD

**Issue by ZiyueWangUoB** [neuralmagic/sparsezoo#100]
Hi, according to this https://sparsezoo.neuralmagic.com/tables/models/cv/detection the yolov3 SPP pruned quantized model (94) should have size around 13MB, but once downloaded using the API I'm getting an onnx model of size 64.5MB? Also when downloading the pruned quantized (97) model I'm getting a model with the same size as the base_none model, both size 251.9MB?

Anyone else having this issue

**Comment by markurtz** [comment]
Hi @ZiyueWangUoB, thanks for filing this. The size listed for pruned quantized is for the compressed ONNX model which will have an extension of .onnx.tar.gz rather than the .onnx extension. This is because unfortunately the .onnx files are protobufs and don't inherently have compression built-in. 

What are the stubs you're using to download the models?

**Comment by jeanniefinks** [comment]
Hello @ZiyueWangUoB 
Let us know if you're able to share the stubs you were using to download the models? 
If we don't hear back, we'll close out this issue in the next few weeks as we'll assume you're all set. Thank you.

**Comment by jeanniefinks** [comment]
Hi @ZiyueWangUoB 
Sounds like you are all set for now so we'll close this issue out for you. Feel free to re-open it if you have more information.
Thank you, Jeannie / Neural Magic
