### ISSUE TITLE
Questions about EfficientNet

### ISSUE THREAD

**Issue by jz-exwzd** [neuralmagic/sparsezoo#145]
Dear Neural Magic Team, may I ask what is the "Arch, Moderate" tag for EfficientNet on the SparseZoo? Does it correspond to any type of pruning? Actually, I tried to prune an EfficientNet on my own, but weirdly couldn't get any good result. So, I wondered if it has been done by the team and started looking in the SparseZoo. If you could give me some hints as to why some models, e.g. EfficientNet, do not respond well to pruning, it would be much appreciated. Thank you.

**Comment by markurtz** [comment]
Hi @jz-exwzd, great question, and thanks for the interest! Unfortunately, EfficientNet models are generally very memory bound and are fairly sensitive to pruning. It's something that we've wanted to look into more in the future, but haven't had a chance to yet. The "Arch, Moderate" tag for EfficientNet stands for a modification to the architecture to enable a better architecture for the DeepSparse engines Tensor Column technology. Specifically, it moves the squeeze excite to the end of the inverted bottleneck blocks rather than having them occur after the depthwise.

In general, models like EfficientNet and those that use the inverted bottleneck with DepthWise convolutions have already been structurally pruned to a very high level because of the DepthWise convolution. Therefore there is less redundancy in the network as compared to a model with larger convolutions such as ResNet's, Inception's, and others. Additionally, EfficientNet's training scheme is not very efficient -- it takes a long time for it to converge to a proper solution, especially on ImageNet. Adding in pruning can destabilize this delicate training process as well.

Hope this helps and let us know if you have any other questions!

**Comment by jz-exwzd** [comment]
Hi @markurtz, thanks for your detailed explanations with the technical details as well.

So the issue is somehow tied to the low redundancy of the EfficientNet, which is the topic of one of the issues that I have raised before regarding the effect of pruning on model's with low redundancy https://github.com/neuralmagic/deepsparse/issues/321. 

It is then not so wise to blindly apply pruning recipes to all kinds of models in hope of getting some form of speed up in all situations. Specifically, pruning could be skipped in small models and some special models like EfficientNet. Was hoping to come up with a mechanism that could work in all situations.

Thank you once again for the explanations that could not be easily discovered by myself.
