### ISSUE TITLE
How to change the input dimensions of the custom ONNX compiled model

### ISSUE THREAD

**Issue by sajalroychowdhury** [neuralmagic/sparsezoo#41]
The current ssd_resnet50_300 takes (300,300) as the input dimensions. My custom trained ONNX model takes in 240,320 as the input dimensions. How can we provide the custom input to the compiled model? I am trying from the detection.ipynb notebook for ssd_resnet50_300 backend.

**Comment by markurtz** [comment]
Hi Sajal, thank you for opening this issue! Unfortunately, the SSD architecture and training schemes are very tightly coupled with the input dimensions, so changing those will require architecture tweaks and most likely retraining. We would recommend if you can, resizing to the 300x300 size through an interpolation. Another option for resizing that preserves aspect ratio would be to resize the image to 225x300 and then padding with zeros to get to 300x300. 

We do have new models that we are adding to the zoo in the coming weeks such as a sparsified YOLO V3 that will enable easily changing the input size and I will update this issue once that is released. Additionally, if there are any models that you would be interested in trying please let us know so we can get them on our roadmap!

**Comment by markurtz** [comment]
Hi @sajalroychowdhury, following up as we recently launched our YOLOv3 models and results. Take a look through the [integration we did with Ultralytics](https://github.com/neuralmagic/sparseml/tree/main/integrations/ultralytics) along with the [accompanying blog post](https://medium.com/limitlessai/yolov3-on-cpus-sparsifying-to-achieve-gpu-level-performance-c2845283e1b0) and let me know if that works for your use case.

Otherwise, let us know if there are any other specific models you'd like to see, and we'll get them added to our roadmap!

Thanks,
Mark

**Comment by jeanniefinks** [comment]
Hello @sajalroychowdhury 
It sounds like you have no further questions or comments here. I'll close this issue out for you. Should you have a follow-up comment, please re-open this thread. For new topics, feel free to open a new GitHub issue or join us in Slack; Slack details are available via this Community page: https://neuralmagic.com/deep-sparse-community/

Cheers, Jeannie / Neural Magic
